In [5]:
import numpy as np

In [7]:
my_list = [1,2,3]

In [9]:
my_list

[1, 2, 3]

In [12]:
arr = np.array(my_list)

In [13]:
my_list

[1, 2, 3]

In [14]:
arr

array([1, 2, 3])

In [15]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [17]:
arr2 = np.array(my_matrix)

In [18]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.zeros(4)

array([0., 0., 0., 0.])

In [29]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
import numpy as np

In [4]:
np.ones(3)

array([1., 1., 1.])

In [6]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.56555768, 0.59788338, 0.82765087, 0.70894861, 0.34880993])

In [13]:
np.random.rand(5,5)

array([[8.32590810e-01, 4.08136182e-01, 4.68147733e-01, 5.76884296e-01,
        3.75164115e-01],
       [9.18702549e-01, 9.77233067e-01, 3.60727058e-01, 7.73272664e-01,
        5.38454920e-01],
       [3.29256378e-01, 1.29953899e-01, 4.22348388e-01, 7.13370127e-02,
        4.33041659e-01],
       [6.55905944e-01, 4.84309987e-01, 9.44186587e-01, 9.56402636e-01,
        5.42136778e-01],
       [5.08793528e-04, 9.90011173e-01, 2.13987667e-01, 4.74689644e-01,
        7.72784101e-01]])

In [15]:
np.random.randn(5)

array([-0.24095559,  0.31329   , -1.58085283, -0.6545758 ,  1.3640307 ])

In [16]:
np.random.randint(1,100)

25

In [17]:
np.random.randint(1,100,10)

array([ 2,  6, 48,  8, 40, 43, 44, 85, 53,  4])

In [18]:
np.random.randint(1,100,100)

array([83,  3,  5, 77, 32, 81, 47, 15, 49, 20, 59, 68, 98, 44,  8, 15, 16,
       92,  2, 49, 52, 25, 27, 84, 31, 76,  4, 89, 22, 79, 82, 19, 30, 75,
       16, 87, 63, 81, 80, 12, 71, 24,  8, 24, 33, 14, 63, 77, 12, 92, 27,
       99, 11, 56, 66,  5, 12, 80, 23, 36, 94, 70,  6,  5, 57, 25, 46, 56,
       12, 18,  9, 48, 60, 84, 46, 60, 62, 86, 38, 45, 92, 45, 43, 76, 74,
       26, 59, 87, 71, 48, 26, 88, 86, 21, 73, 11, 20, 92, 81, 27])

In [19]:
arr = np.arange(25)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranarr = np.random.randint(0,50,10)

In [22]:
ranarr

array([49,  7, 30, 44,  8, 45, 49, 46,  4, 44])

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr.max()

49

In [25]:
ranarr.min()

4

In [26]:
ranarr.argmin()

8

In [27]:
ranarr.argmax()

0

In [29]:
arr.shape

(25,)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr.shape

(25,)

In [34]:
arr.dtype

dtype('int32')